@base_url = http://localhost:3000/api/v1

GET {{base_url}}/microcontroller/identify/00:11:22:33:44:55

###

POST {{base_url}}/coordinates
Content-Type: application/json

{
  "latitude": 12.345678,
  "longitude": 23.456789,
  "microcontrollerId": "cmbvi5ie20002casxa8gjaxlm"
}